from _typeshed import Incomplete

com: Incomplete

def com_page(error: int = ...) -> None: ...

ports: Incomplete
ser: Incomplete

def prepare_for_parknig(park_n) -> None: ...
def park(park_n) -> None: ...
def getcar(park_n) -> None: ...
