def message(window, text, type) -> None: ...
def park_wait_page(): ...
def park_page_1(): ...
def park_button(): ...
def get_wait_page() -> None: ...
def pay_page() -> None: ...
def password_page(): ...
def get_car_page(): ...
def root_page() -> None: ...
