def make_timer_obj(frame, id_pos, timer, **extraArgs): ...
def make_rectangle_obj(frame, id_dimension, color, **extraArgs): ...
def get_pos(frame_shape, id_dimension): ...
def check_gpu_accl(_default_gpu: int = ...): ...
def enable_multithreading(thread_no: int = ...): ...
def video_settings_setup(cam_indx: int = ..., fps: int = ..., vid_length_sec: int = ..., res=..., flscreen: bool = ...): ...
def compare_img(img_to_comp, ref_img): ...
def get_trans_mat(good_matches, key_points): ...
def get_skew_angle(homograph_rot_mat, img_to_skew_shape): ...
def affine_trans(_skew_angle, img_coord, _image_to_skew): ...
def rotate_180(img_to_rotate_180): ...
def deskew_img(img_to_skew, ref_img, **extraArgs): ...

skipped_cnt: int
sec_passed: int

def process_vid_frame(_frame, _id_dimension, _is_valid, _is_valid2, _ref_img, **extraArgs): ...
def search_id(id_char_type, scanned_image, valid_ids_freq): ...
def read_simple_card_cuda(vid, vid_specs, id_card_specs, is_valid: bool = ...): ...
def read_simple_card_opencl(vid, vid_specs, id_card_specs, is_valid: bool = ..., is_valid2: bool = ...): ...
def ocr_ready_id(frames_buff, frames_deskewed_buff, id_card_specs, fps): ...
def save_ref_img_db(name: str = ...) -> None: ...
def get_ref_img_db(img_name: str = ...): ...
def ocr_main(id_dimension: tuple = ..., id_type_indx: int = ..., testing_on: bool = ...) -> str: ...
