from database_data import *
import numpy as np
import sqlite3

def connect_db(): ...
def create_db(conn) -> None: ...
def build_db() -> None: ...
def is_full(): ...
def validate_pass(pass_to_check: str, id, cursor: sqlite3.Cursor) -> bool: ...
def calc_cost(person_id: str, car: str, conn: sqlite3.Connection): ...
def park_car_db(conn, cmd, id, temp_pass: str): ...
def send_pop_unsended_emails(conn: sqlite3.Connection, id: str) -> enm: ...
def get_car_db(conn, cmd, id, pass_to_check: str): ...
def db_check_ai_id(id_to_chk: str) -> bool: ...
def access_img_table(readOrwrite: bool, img_to_write: np.ndarray = ..., img_name: str = ..., ref_id_val: str = ...): ...
def db_cmd(cmd: int, id: str = ..., temp_password: str = ...): ...
